### PR TITLE
Make Holy Parser unholy

### PR DESCRIPTION
**Pull request by y3th**
i hate jesus and i make this unholy

### CODE REVIEW

**Comment by funyeatsalad** [comment]
FUCK YOU, JESUS DOES NOT WANT OPTIMIZATION, JESUS WANTS PEOPLE TO WORK LIKE MAN, FUCK YOU

**Comment by funyeatsalad** [comment]
FUCK YOU SINNER, JESUS DOES NOT WANT FUNCTIONS FUCKER

**Comment by y3th** [comment]
I Added One funciton

**Comment by funyeatsalad** [comment]
shut up bitch

**Comment by funyeatsalad** [comment]
fine

**Pull request merged**
